-- =====================================================================
-- Script de preparacion del SGBD Oracle para el microservicio
-- Motor: Oracle Database 23ai Free  (PDB: FREEPDB1, puerto 1521)
-- =====================================================================
-- COMO EJECUTARLO (en SQL*Plus o SQL Developer):
--   1) Conectate como administrador a la PDB FREEPDB1:
--        sqlplus system/TuPassword@localhost:1521/FREEPDB1
--   2) Pega la PARTE 1 (crear usuario con cuota).
--   3) Reconectate como el nuevo usuario:
--        CONNECT alumno_sgbd/Alumno123@localhost:1521/FREEPDB1
--   4) Pega la PARTE 2 (tabla y datos de prueba).
-- =====================================================================

-- ---------- PARTE 1: usuario con cuota de espacio (ejecutar como SYSTEM)
CREATE USER alumno_sgbd IDENTIFIED BY Alumno123
  DEFAULT TABLESPACE users
  QUOTA 100M ON users;

GRANT CONNECT, RESOURCE TO alumno_sgbd;
GRANT CREATE SESSION, CREATE TABLE TO alumno_sgbd;

-- ---------- PARTE 2: tabla y datos (ejecutar como alumno_sgbd)
CREATE TABLE estudiantes (
  id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR2(100) NOT NULL,
  email          VARCHAR2(100) NOT NULL UNIQUE,
  matricula      VARCHAR2(20)  NOT NULL UNIQUE,
  fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP,
  estado         VARCHAR2(10) DEFAULT 'activo'
                 CHECK (estado IN ('activo','inactivo'))
);

INSERT INTO estudiantes (nombre, email, matricula)
  VALUES ('Juan Garcia', 'juan.garcia@email.com', 'EST001');
INSERT INTO estudiantes (nombre, email, matricula)
  VALUES ('Maria Lopez', 'maria.lopez@email.com', 'EST002');
INSERT INTO estudiantes (nombre, email, matricula)
  VALUES ('Carlos Rodriguez', 'carlos.rodriguez@email.com', 'EST003');

COMMIT;

SELECT 'Base de datos Oracle lista' AS resultado FROM dual;
