server:
  port: 8080

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost:3306/abd_students?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "01102001"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    # Muestra las consultas SQL generadas por Hibernate en los logs
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: false

# Configuracion de logs para monitorear el comportamiento del microservicio
logging:
  level:
    root: INFO
    com.abd.student: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
