# ===== Microservicio Student =====
# Puerto en el que Angular lo consume: http://<ip-linux>:8090
server.port=8090

# ===== Conexión a PostgreSQL (en el mismo servidor Linux) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/escuela
spring.datasource.username=postgres
spring.datasource.password=CAMBIA_ESTA_CONTRASENA
spring.datasource.driver-class-name=org.postgresql.Driver

# No modificar el esquema automáticamente (las tablas se crean con el script SQL)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
